### ISSUE TITLE
Usabilidade: cadastro de proprietário a partir de propriedade.

### ISSUE THREAD

**Issue by kellisonjk** [NutriCampus/NutriCampus#10]
No cadastro de propriedade, ao cadastrar um proprietário a partir do botão de novo proprietário, o novo proprietário deveria ser selecionado automaticamente no spinner da tela de cadastro de propriedade.

**Comment by fgpacheco** [comment]
Corrigido.

**Comment by kellisonjk** [comment]
(corrigido em meio aos commits do desenvolvimento da Release 03)
