### ISSUE TITLE
kellisonjk: Filtro de propriedade na activity ANIMAIS não funcionando

### ISSUE THREAD

**Issue by TroniPM** [NutriCampus/NutriCampus#16]
Ao selecionar uma propriedade, os animais na tela permanecem inalterados, mostrando todos os animais cadastrados, independente da propriedade selecionada.

**Comment by kellisonjk** [comment]
Funcionalidade estava em fase de término no momento da criação do issue.

**Comment by fgpacheco** [comment]
Corrigido.
