### ISSUE TITLE
kellisonjk: Activity PROPRIEDADES: quantidade errada sendo mostrada no "primeiro acesso"

### ISSUE THREAD

**Issue by TroniPM** [NutriCampus/NutriCampus#17]
Ao acessar activity PROPRIEDADES, mesmo sem cadastrar nenhum propriedade, mostra que tem um propriedade cadastrada, mesmo sem haver.

**Comment by kellisonjk** [comment]
Esse bug seria na activity de Animais, não?

**Comment by kellisonjk** [comment]
Foi corrigido em um momento anterior ao da criação do issue (o commit ainda não havia sido feito)
